name: Sync devops-class

on:
  schedule:
    - cron: '*/2 * * * *'  # Set your desired cron schedule

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: ranjan.singh8119@gmail.com

      - name: Push to Target Repository
        run: |
          git remote add origin https://gitlab.com/ranjanj3/deployment.git
         git push -uf origin main
        env:
          GITHUB_TOKEN: ${{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}}
