name: Scheduled Sync to GitLab

on:
  schedule:
    - cron: '*/1 * * * *'  # Set the schedule for midnight every day

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Change this to 20

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
        
            
            git remote set-url origin https://gitlab.com/ranjanj3/deployment.git

            git remote add origin https://gitlab.com/ranjanj3/deployment.git
            git branch -M main
            git push gitlab main


      
        env:
          GITLAB_TOKEN: ${{ secrets.glpat-GGB6ssKsZBeEo_AzUR3S }}
