name: Scheduled Sync to GitLab

on:
  schedule:
    - cron: '*/2 * * * *'  # Set the schedule for midnight every day

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
         git remote add origin https://gitlab.com/ranjanj3/deployment.git
          git push gitlab HEAD:main  # Adjust this to your target branch on GitLab
        env:
          GITLAB_TOKEN: ${{ glpat-GGB6ssKsZBeEo_AzUR3S }}
